networks:
  pcalerts-network:
    name: pcalerts-network

volumes:
  mysql-data:

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pcalerts
      MYSQL_USER: pcalerts
      MYSQL_PASSWORD: pcalerts
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - pcalerts-network
    ports:
      - "8952:3306"
    restart: unless-stopped
