networks:
  pcalerts-network:
    name: pcalerts-network
    external: true

services:
  php:
    container_name: pcalerts-php
    env_file:
      - .env
    networks:
      - pcalerts-network
    restart: unless-stopped

  caddy:
    container_name: caddy
    depends_on:
      - php
    ports:
      - "8950:80"
    networks:
      - pcalerts-network
    restart: unless-stopped
